-- StockLens optional cloud schema for Supabase Postgres
create table if not exists public.stock_records (
  id bigint generated by default as identity primary key,
  record_id text,
  record_date date,
  status text,
  wing text,
  party_name text,
  product_detail text,
  model_group text,
  brand text,
  imei_serial text,
  imei_key text,
  sales_employee text,
  source_file text,
  source_sheet text,
  quantity numeric default 1,
  color_note text,
  unit_count numeric default 1,
  imei_type text,
  imei_occurrences integer default 1,
  duplicate_imei boolean default false,
  fingerprint text unique,
  created_at timestamptz default now()
);
create index if not exists stock_records_imei_key_idx on public.stock_records(imei_key);
create index if not exists stock_records_record_date_idx on public.stock_records(record_date);
create table if not exists public.stock_allocations (
  id bigint generated by default as identity primary key,
  seller text not null,
  model text not null,
  quantity numeric not null default 1,
  created_at timestamptz default now()
);
create table if not exists public.stock_offers (
  id bigint generated by default as identity primary key,
  client text not null,
  model text not null,
  quantity numeric not null default 1,
  price numeric not null default 0,
  currency text not null default 'BDT',
  note text,
  created_at timestamptz default now()
);
-- For a public/internal deployment, configure RLS and policies to match your team auth.
-- Do not expose a service_role key in frontend code.
